return {
	"jakob.plugins.colorscheme",
	"jakob.plugins.autopairs",
	"jakob.plugins.blink",
	"jakob.plugins.conform",
	"jakob.plugins.fugitive",
	"jakob.plugins.indent",
	"jakob.plugins.lualine",
	"jakob.plugins.mason",
	"jakob.plugins.nvimtree",
	"jakob.plugins.telescope",
	"jakob.plugins.tmux-navigator",
	"jakob.plugins.treesitter",
	"jakob.plugins.undotree",
	"jakob.plugins.whichkey",
}
